name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: List coverage files for debugging
        run: ls -R ./coverage

      - name: Generate coverage report
        run: npm run coverage

      - name: Save coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ./coverage/

  check-coverage:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download coverage report
        uses: actions/download-artifact@v3
        with:
          name: coverage-report

      - name: Check if coverage-summary.json exists
        run: |
          ls ./coverage
          if [ ! -f ./coverage/coverage-summary.json ]; then
            echo "Coverage report not found!"
            exit 1
          fi
          echo "Coverage report found"

      - name: Check test coverage
        run: |
          COVERAGE=$(cat ./coverage/coverage-summary.json | jq .total.lines.pct)
          echo "Test coverage is ${COVERAGE}%"
          if (( $(echo "$COVERAGE < 90" | bc -l) )); then
            echo "Test coverage is below 90%, cannot proceed."
            exit 1
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: check-coverage
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install modules
        run: npm install

      - name: Build dist
        run: npm run build

      - name: Setup pages
        uses: actions/configure-pages@v3

      - name: Upload dist folder
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./dist"

      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v1
